import Head from 'next/head'
import axios from 'axios'

import { Video } from '@/types'
import { VideoCard, NoResults } from '@/components'
import { BASE_URL } from '@/utils'

interface IProps {
  videos: Video[]
}

const Home = ({ videos }: IProps) => {

  return (
    <>
      <Head>
        <title>TIK TUNG - The Best SocialMedia WebSide.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/tiktung-logo.512.png" />
      </Head>
      <main>
        <div className='flex flex-col gap-10 videos h-full'>
          {videos?.length ? (
            videos.map((video: Video) => (
              <VideoCard post={video} key={video._id} />
            ))

          ) : (
            <NoResults text={'There are no Videos'} />
          )}
        </div>
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  const { data } = await axios.get(`${BASE_URL}/api/post`)

  return {
    props: {
      videos: data,
    }
  }
}

export default Home