import Head from 'next/head'
import axios from 'axios'

import { Video } from '@/types'
import { VideoCard, NoResults } from '@/components'
import { BASE_URL } from '@/utils'

interface IProps {
  videos: Video[]
}

const Home = ({ videos }: IProps) => {


  return (
    <>
      <Head>
        <title>TIK TUNG - The Best SocialMedia WebSide.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/tiktung-logo.512.png" />
      </Head>
      <main>
        <div className='flex flex-col gap-10 videos h-full'>
          {videos?.length ? (
            videos.map((video: Video) => (
              <div id={video._id}>
                <VideoCard post={video} key={video._id} />
              </div>
            ))

          ) : <NoResults text='There are no videos...' />}
        </div>
      </main>
    </>
  )
}

export const getServerSideProps = async ({
  query: { topic }
}: {
  query: { topic: string }
}) => {
  let response = null

  if (topic) {
    response = await axios.get(`${BASE_URL}/api/discover/${topic}`)
  } else {
    response = await axios.get(`${BASE_URL}/api/post`)
  }

  return {
    props: {
      videos: response.data,
    }
  }
}

export default Home